// Project actions
export const SET_PROJECTS = 'SET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_CURRENT_PROJECT_ID = 'SET_CURRENT_PROJECT_ID';

// Legacy session actions (for migration period)
export const SET_SESSIONS = 'SET_SESSIONS';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';
export const SET_CURRENT_SESSION_ID = 'SET_CURRENT_SESSION_ID';

// Batch actions
export const SET_BATCH_JOBS = 'SET_BATCH_JOBS';
export const ADD_BATCH_JOB = 'ADD_BATCH_JOB';
export const UPDATE_BATCH_JOB = 'UPDATE_BATCH_JOB';
export const DELETE_BATCH_JOB = 'DELETE_BATCH_JOB';
export const SET_SELECTED_BATCH_JOB_ID = 'SET_SELECTED_BATCH_JOB_ID';
export const SET_BATCH_GENERATING = 'SET_BATCH_GENERATING';
export const SET_BATCH_GENERATION_PROGRESS = 'SET_BATCH_GENERATION_PROGRESS';
export const SET_REFINING_SLOT_IDS = 'SET_REFINING_SLOT_IDS';

// Library actions
export const SET_MODELS = 'SET_MODELS';
export const ADD_MODEL = 'ADD_MODEL';
export const UPDATE_MODEL = 'UPDATE_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_TEMPLATES = 'SET_TEMPLATES';

// Team actions
export const SET_TEAMS = 'SET_TEAMS';
export const SET_CURRENT_TEAM_ID = 'SET_CURRENT_TEAM_ID';
export const ADD_TEAM = 'ADD_TEAM';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const DELETE_TEAM = 'DELETE_TEAM';

// UI actions
export const SET_GENERATING = 'SET_GENERATING';
export const SET_GENERATION_STAGE = 'SET_GENERATION_STAGE';
export const SET_GENERATION_PROGRESS = 'SET_GENERATION_PROGRESS';
export const SET_ENHANCING = 'SET_ENHANCING';
export const SET_PREVIEW_IMAGE = 'SET_PREVIEW_IMAGE';
export const SET_ERROR_DETAILS = 'SET_ERROR_DETAILS';
export const SET_MASK_EDIT_CONTEXT = 'SET_MASK_EDIT_CONTEXT';
export const SET_MASK_HISTORY_ITEMS = 'SET_MASK_HISTORY_ITEMS';
export const SET_ADVANCED_PANEL_OPEN = 'SET_ADVANCED_PANEL_OPEN';
export const SET_QUEUE_STATS = 'SET_QUEUE_STATS';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';
export const SET_SELECTED_IMAGE = 'SET_SELECTED_IMAGE';
export const SET_API_CONFIG = 'SET_API_CONFIG';
export const SET_DEFAULT_PREFERENCES = 'SET_DEFAULT_PREFERENCES';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_READY = 'SET_AUTH_READY';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_IS_SUPER_ADMIN = 'SET_IS_SUPER_ADMIN';
